### ISSUE TITLE
Wrong name when installing as an helm dependency

### ISSUE THREAD

**Issue by AnakinPt** [hivemq/helm-charts#97]
I use the Helm chart as a dependency of another service I use, so I can ramp up everything at once.

In my chart.yaml file I added this:
```
dependencies:
  - name: hivemq-operator
    version: 0.11.17
    repository: https://hivemq.github.io/helm-charts
    condition: hivemq-operator.enabled
```

then in the values.yamlI added this:
```
hivemq-operator:
  enabled: true
  namespaceOverride: hivemq
  nameOverride: hivemq
  fullnameOverride: hivemq
  global:
    rbac:
      pspEnabled: false
```

When I run the command:
```
helm upgrade -i foo .
```

I expect to have in the hivemq namespace a deployment named hivemq for the cluster, but I found 3 pods named "foo".

I presume this happens because in the cluster-deployment.yaml file it's using "{{ spec.name }}" and not allowing a name override from the user.
